% Wiezy = struct('typ',{},... % dopisanych czy kinematyczny
%     'klasa',{},... % para postepowa czy obrotowa (innych na razie nie ma)
%     'bodyi',{},... % numer pierwszego ciala
%     'bodyj',{},... % numer drugiego ciala
%     'sA',{},... % wektor sA w i-tym ukladzie
%     'sB',{},... % wektor sB w j-tym ukladzie
%     'phi0',{},... % kat phi0 (jezeli para obrotowa - nie uzywamy)
%     'perp',{},... % wersor prostopadly osi ruchu w ukladzie jtym! (jezeli para obrotowa - nie uzywamy)
%     'fodt',{},... % funkcja od czasu dla wiezow dopisanych
%     'dotfodt',{},... % pochodna funkcji od czasu dla wiezow dopisanych
%     'ddotfodt',{}) % druga pochodna funkcji od czasu dla wiezow dopisanych

Wiezy(1) = cell2struct(...
    {'kinematyczny', 'obrotowy', 1, 4,  [0.8;-0.4], [-0.05;-0.25], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt A
Wiezy(2) = cell2struct(...
    {'kinematyczny', 'obrotowy', 4, 5,  [-0.25; 0.35], [0.4; -0.2], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt B
Wiezy(3) = cell2struct(...
    {'kinematyczny', 'obrotowy', 3, 5,  [0.3; 0.1], [-0.4; 0.2], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt C
Wiezy(4) = cell2struct(...
    {'kinematyczny', 'obrotowy', 1, 10,  [0.1; 0.2], [0.1; 0], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt D
Wiezy(5) = cell2struct(...
    {'kinematyczny', 'obrotowy', 3, 10,  [0.3; -0.1], [-0.2; 0.2], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt E
Wiezy(6) = cell2struct(...
    {'kinematyczny', 'obrotowy', 2, 3,  [-0.3; 0.1], [-0.5; 0], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt F
Wiezy(7) = cell2struct(...
    {'kinematyczny', 'obrotowy', 2, 9,  [0.3; 0.1], [0.05; 0.25], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt G
Wiezy(8) = cell2struct(...
    {'kinematyczny', 'obrotowy', 0, 8,  [0.1; -0.7], [-0.05; -0.25], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt H
Wiezy(9) = cell2struct(...
    {'kinematyczny', 'obrotowy', 7, 10,  [0.2; 0.05], [0.1; -0.2], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt M
Wiezy(10) = cell2struct(...
    {'kinematyczny', 'obrotowy', 0, 6,  [0; -0.4], [-0.2; -0.05], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt N
Wiezy(11) = cell2struct(...
    {'kinematyczny', 'obrotowy', 0, 2,  [0; 0], [0; -0.2], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt O
Wiezy(12) = cell2struct(...
    {'kinematyczny', 'obrotowy', 1, 2,  [-0.9; 0.3], [-0.2; -0.1], [], [], [], [], []}', ...
    fieldnames(Wiezy)); % Punkt P
Wiezy(13) = cell2struct(...
    {'kinematyczny', 'postepowy', 6, 7,  [-0.2; -0.05], [0.2; 0.05], 0, [-1;4]/sqrt(17), [], [], []}', ...
    fieldnames(Wiezy)); % Punkt NM
Wiezy(14) = cell2struct(...
    {'kinematyczny', 'postepowy', 8, 9,  [-0.05; -0.25], [0.05; 0.25], 0, [-5;1]/sqrt(26), [], [], []}', ...
    fieldnames(Wiezy)); % Punkt HG